// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("IDProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDProduct"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IDProduct");

                    b.ToTable("Products", "Catalog");

                    b.HasData(
                        new
                        {
                            IDProduct = 1,
                            Description = "Description for product 1",
                            Name = "Product 1",
                            Price = 952m
                        },
                        new
                        {
                            IDProduct = 2,
                            Description = "Description for product 2",
                            Name = "Product 2",
                            Price = 559m
                        },
                        new
                        {
                            IDProduct = 3,
                            Description = "Description for product 3",
                            Name = "Product 3",
                            Price = 947m
                        },
                        new
                        {
                            IDProduct = 4,
                            Description = "Description for product 4",
                            Name = "Product 4",
                            Price = 189m
                        },
                        new
                        {
                            IDProduct = 5,
                            Description = "Description for product 5",
                            Name = "Product 5",
                            Price = 332m
                        },
                        new
                        {
                            IDProduct = 6,
                            Description = "Description for product 6",
                            Name = "Product 6",
                            Price = 854m
                        },
                        new
                        {
                            IDProduct = 7,
                            Description = "Description for product 7",
                            Name = "Product 7",
                            Price = 423m
                        },
                        new
                        {
                            IDProduct = 8,
                            Description = "Description for product 8",
                            Name = "Product 8",
                            Price = 833m
                        },
                        new
                        {
                            IDProduct = 9,
                            Description = "Description for product 9",
                            Name = "Product 9",
                            Price = 278m
                        },
                        new
                        {
                            IDProduct = 10,
                            Description = "Description for product 10",
                            Name = "Product 10",
                            Price = 151m
                        },
                        new
                        {
                            IDProduct = 11,
                            Description = "Description for product 11",
                            Name = "Product 11",
                            Price = 322m
                        },
                        new
                        {
                            IDProduct = 12,
                            Description = "Description for product 12",
                            Name = "Product 12",
                            Price = 383m
                        },
                        new
                        {
                            IDProduct = 13,
                            Description = "Description for product 13",
                            Name = "Product 13",
                            Price = 887m
                        },
                        new
                        {
                            IDProduct = 14,
                            Description = "Description for product 14",
                            Name = "Product 14",
                            Price = 631m
                        },
                        new
                        {
                            IDProduct = 15,
                            Description = "Description for product 15",
                            Name = "Product 15",
                            Price = 550m
                        },
                        new
                        {
                            IDProduct = 16,
                            Description = "Description for product 16",
                            Name = "Product 16",
                            Price = 794m
                        },
                        new
                        {
                            IDProduct = 17,
                            Description = "Description for product 17",
                            Name = "Product 17",
                            Price = 459m
                        },
                        new
                        {
                            IDProduct = 18,
                            Description = "Description for product 18",
                            Name = "Product 18",
                            Price = 775m
                        },
                        new
                        {
                            IDProduct = 19,
                            Description = "Description for product 19",
                            Name = "Product 19",
                            Price = 537m
                        },
                        new
                        {
                            IDProduct = 20,
                            Description = "Description for product 20",
                            Name = "Product 20",
                            Price = 650m
                        },
                        new
                        {
                            IDProduct = 21,
                            Description = "Description for product 21",
                            Name = "Product 21",
                            Price = 744m
                        },
                        new
                        {
                            IDProduct = 22,
                            Description = "Description for product 22",
                            Name = "Product 22",
                            Price = 790m
                        },
                        new
                        {
                            IDProduct = 23,
                            Description = "Description for product 23",
                            Name = "Product 23",
                            Price = 110m
                        },
                        new
                        {
                            IDProduct = 24,
                            Description = "Description for product 24",
                            Name = "Product 24",
                            Price = 288m
                        },
                        new
                        {
                            IDProduct = 25,
                            Description = "Description for product 25",
                            Name = "Product 25",
                            Price = 941m
                        },
                        new
                        {
                            IDProduct = 26,
                            Description = "Description for product 26",
                            Name = "Product 26",
                            Price = 738m
                        },
                        new
                        {
                            IDProduct = 27,
                            Description = "Description for product 27",
                            Name = "Product 27",
                            Price = 813m
                        },
                        new
                        {
                            IDProduct = 28,
                            Description = "Description for product 28",
                            Name = "Product 28",
                            Price = 361m
                        },
                        new
                        {
                            IDProduct = 29,
                            Description = "Description for product 29",
                            Name = "Product 29",
                            Price = 509m
                        },
                        new
                        {
                            IDProduct = 30,
                            Description = "Description for product 30",
                            Name = "Product 30",
                            Price = 996m
                        },
                        new
                        {
                            IDProduct = 31,
                            Description = "Description for product 31",
                            Name = "Product 31",
                            Price = 915m
                        },
                        new
                        {
                            IDProduct = 32,
                            Description = "Description for product 32",
                            Name = "Product 32",
                            Price = 422m
                        },
                        new
                        {
                            IDProduct = 33,
                            Description = "Description for product 33",
                            Name = "Product 33",
                            Price = 346m
                        },
                        new
                        {
                            IDProduct = 34,
                            Description = "Description for product 34",
                            Name = "Product 34",
                            Price = 146m
                        },
                        new
                        {
                            IDProduct = 35,
                            Description = "Description for product 35",
                            Name = "Product 35",
                            Price = 321m
                        },
                        new
                        {
                            IDProduct = 36,
                            Description = "Description for product 36",
                            Name = "Product 36",
                            Price = 251m
                        },
                        new
                        {
                            IDProduct = 37,
                            Description = "Description for product 37",
                            Name = "Product 37",
                            Price = 249m
                        },
                        new
                        {
                            IDProduct = 38,
                            Description = "Description for product 38",
                            Name = "Product 38",
                            Price = 640m
                        },
                        new
                        {
                            IDProduct = 39,
                            Description = "Description for product 39",
                            Name = "Product 39",
                            Price = 804m
                        },
                        new
                        {
                            IDProduct = 40,
                            Description = "Description for product 40",
                            Name = "Product 40",
                            Price = 407m
                        },
                        new
                        {
                            IDProduct = 41,
                            Description = "Description for product 41",
                            Name = "Product 41",
                            Price = 758m
                        },
                        new
                        {
                            IDProduct = 42,
                            Description = "Description for product 42",
                            Name = "Product 42",
                            Price = 350m
                        },
                        new
                        {
                            IDProduct = 43,
                            Description = "Description for product 43",
                            Name = "Product 43",
                            Price = 856m
                        },
                        new
                        {
                            IDProduct = 44,
                            Description = "Description for product 44",
                            Name = "Product 44",
                            Price = 866m
                        },
                        new
                        {
                            IDProduct = 45,
                            Description = "Description for product 45",
                            Name = "Product 45",
                            Price = 803m
                        },
                        new
                        {
                            IDProduct = 46,
                            Description = "Description for product 46",
                            Name = "Product 46",
                            Price = 566m
                        },
                        new
                        {
                            IDProduct = 47,
                            Description = "Description for product 47",
                            Name = "Product 47",
                            Price = 949m
                        },
                        new
                        {
                            IDProduct = 48,
                            Description = "Description for product 48",
                            Name = "Product 48",
                            Price = 151m
                        },
                        new
                        {
                            IDProduct = 49,
                            Description = "Description for product 49",
                            Name = "Product 49",
                            Price = 827m
                        },
                        new
                        {
                            IDProduct = 50,
                            Description = "Description for product 50",
                            Name = "Product 50",
                            Price = 596m
                        },
                        new
                        {
                            IDProduct = 51,
                            Description = "Description for product 51",
                            Name = "Product 51",
                            Price = 744m
                        },
                        new
                        {
                            IDProduct = 52,
                            Description = "Description for product 52",
                            Name = "Product 52",
                            Price = 625m
                        },
                        new
                        {
                            IDProduct = 53,
                            Description = "Description for product 53",
                            Name = "Product 53",
                            Price = 749m
                        },
                        new
                        {
                            IDProduct = 54,
                            Description = "Description for product 54",
                            Name = "Product 54",
                            Price = 210m
                        },
                        new
                        {
                            IDProduct = 55,
                            Description = "Description for product 55",
                            Name = "Product 55",
                            Price = 461m
                        },
                        new
                        {
                            IDProduct = 56,
                            Description = "Description for product 56",
                            Name = "Product 56",
                            Price = 722m
                        },
                        new
                        {
                            IDProduct = 57,
                            Description = "Description for product 57",
                            Name = "Product 57",
                            Price = 893m
                        },
                        new
                        {
                            IDProduct = 58,
                            Description = "Description for product 58",
                            Name = "Product 58",
                            Price = 931m
                        },
                        new
                        {
                            IDProduct = 59,
                            Description = "Description for product 59",
                            Name = "Product 59",
                            Price = 141m
                        },
                        new
                        {
                            IDProduct = 60,
                            Description = "Description for product 60",
                            Name = "Product 60",
                            Price = 620m
                        },
                        new
                        {
                            IDProduct = 61,
                            Description = "Description for product 61",
                            Name = "Product 61",
                            Price = 529m
                        },
                        new
                        {
                            IDProduct = 62,
                            Description = "Description for product 62",
                            Name = "Product 62",
                            Price = 661m
                        },
                        new
                        {
                            IDProduct = 63,
                            Description = "Description for product 63",
                            Name = "Product 63",
                            Price = 812m
                        },
                        new
                        {
                            IDProduct = 64,
                            Description = "Description for product 64",
                            Name = "Product 64",
                            Price = 531m
                        },
                        new
                        {
                            IDProduct = 65,
                            Description = "Description for product 65",
                            Name = "Product 65",
                            Price = 130m
                        },
                        new
                        {
                            IDProduct = 66,
                            Description = "Description for product 66",
                            Name = "Product 66",
                            Price = 746m
                        },
                        new
                        {
                            IDProduct = 67,
                            Description = "Description for product 67",
                            Name = "Product 67",
                            Price = 853m
                        },
                        new
                        {
                            IDProduct = 68,
                            Description = "Description for product 68",
                            Name = "Product 68",
                            Price = 591m
                        },
                        new
                        {
                            IDProduct = 69,
                            Description = "Description for product 69",
                            Name = "Product 69",
                            Price = 712m
                        },
                        new
                        {
                            IDProduct = 70,
                            Description = "Description for product 70",
                            Name = "Product 70",
                            Price = 325m
                        },
                        new
                        {
                            IDProduct = 71,
                            Description = "Description for product 71",
                            Name = "Product 71",
                            Price = 842m
                        },
                        new
                        {
                            IDProduct = 72,
                            Description = "Description for product 72",
                            Name = "Product 72",
                            Price = 924m
                        },
                        new
                        {
                            IDProduct = 73,
                            Description = "Description for product 73",
                            Name = "Product 73",
                            Price = 887m
                        },
                        new
                        {
                            IDProduct = 74,
                            Description = "Description for product 74",
                            Name = "Product 74",
                            Price = 758m
                        },
                        new
                        {
                            IDProduct = 75,
                            Description = "Description for product 75",
                            Name = "Product 75",
                            Price = 359m
                        },
                        new
                        {
                            IDProduct = 76,
                            Description = "Description for product 76",
                            Name = "Product 76",
                            Price = 689m
                        },
                        new
                        {
                            IDProduct = 77,
                            Description = "Description for product 77",
                            Name = "Product 77",
                            Price = 215m
                        },
                        new
                        {
                            IDProduct = 78,
                            Description = "Description for product 78",
                            Name = "Product 78",
                            Price = 595m
                        },
                        new
                        {
                            IDProduct = 79,
                            Description = "Description for product 79",
                            Name = "Product 79",
                            Price = 706m
                        },
                        new
                        {
                            IDProduct = 80,
                            Description = "Description for product 80",
                            Name = "Product 80",
                            Price = 855m
                        },
                        new
                        {
                            IDProduct = 81,
                            Description = "Description for product 81",
                            Name = "Product 81",
                            Price = 881m
                        },
                        new
                        {
                            IDProduct = 82,
                            Description = "Description for product 82",
                            Name = "Product 82",
                            Price = 250m
                        },
                        new
                        {
                            IDProduct = 83,
                            Description = "Description for product 83",
                            Name = "Product 83",
                            Price = 967m
                        },
                        new
                        {
                            IDProduct = 84,
                            Description = "Description for product 84",
                            Name = "Product 84",
                            Price = 527m
                        },
                        new
                        {
                            IDProduct = 85,
                            Description = "Description for product 85",
                            Name = "Product 85",
                            Price = 846m
                        },
                        new
                        {
                            IDProduct = 86,
                            Description = "Description for product 86",
                            Name = "Product 86",
                            Price = 149m
                        },
                        new
                        {
                            IDProduct = 87,
                            Description = "Description for product 87",
                            Name = "Product 87",
                            Price = 805m
                        },
                        new
                        {
                            IDProduct = 88,
                            Description = "Description for product 88",
                            Name = "Product 88",
                            Price = 402m
                        },
                        new
                        {
                            IDProduct = 89,
                            Description = "Description for product 89",
                            Name = "Product 89",
                            Price = 577m
                        },
                        new
                        {
                            IDProduct = 90,
                            Description = "Description for product 90",
                            Name = "Product 90",
                            Price = 370m
                        },
                        new
                        {
                            IDProduct = 91,
                            Description = "Description for product 91",
                            Name = "Product 91",
                            Price = 995m
                        },
                        new
                        {
                            IDProduct = 92,
                            Description = "Description for product 92",
                            Name = "Product 92",
                            Price = 935m
                        },
                        new
                        {
                            IDProduct = 93,
                            Description = "Description for product 93",
                            Name = "Product 93",
                            Price = 123m
                        },
                        new
                        {
                            IDProduct = 94,
                            Description = "Description for product 94",
                            Name = "Product 94",
                            Price = 380m
                        },
                        new
                        {
                            IDProduct = 95,
                            Description = "Description for product 95",
                            Name = "Product 95",
                            Price = 281m
                        },
                        new
                        {
                            IDProduct = 96,
                            Description = "Description for product 96",
                            Name = "Product 96",
                            Price = 253m
                        },
                        new
                        {
                            IDProduct = 97,
                            Description = "Description for product 97",
                            Name = "Product 97",
                            Price = 746m
                        },
                        new
                        {
                            IDProduct = 98,
                            Description = "Description for product 98",
                            Name = "Product 98",
                            Price = 455m
                        },
                        new
                        {
                            IDProduct = 99,
                            Description = "Description for product 99",
                            Name = "Product 99",
                            Price = 100m
                        },
                        new
                        {
                            IDProduct = 100,
                            Description = "Description for product 100",
                            Name = "Product 100",
                            Price = 677m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("IDProductInStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDProductInStock"));

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("IDProductInStock");

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.ToTable("Stocks", "Catalog");

                    b.HasData(
                        new
                        {
                            IDProductInStock = 1,
                            ProductID = 1,
                            Stock = 16
                        },
                        new
                        {
                            IDProductInStock = 2,
                            ProductID = 2,
                            Stock = 2
                        },
                        new
                        {
                            IDProductInStock = 3,
                            ProductID = 3,
                            Stock = 13
                        },
                        new
                        {
                            IDProductInStock = 4,
                            ProductID = 4,
                            Stock = 12
                        },
                        new
                        {
                            IDProductInStock = 5,
                            ProductID = 5,
                            Stock = 15
                        },
                        new
                        {
                            IDProductInStock = 6,
                            ProductID = 6,
                            Stock = 5
                        },
                        new
                        {
                            IDProductInStock = 7,
                            ProductID = 7,
                            Stock = 13
                        },
                        new
                        {
                            IDProductInStock = 8,
                            ProductID = 8,
                            Stock = 14
                        },
                        new
                        {
                            IDProductInStock = 9,
                            ProductID = 9,
                            Stock = 16
                        },
                        new
                        {
                            IDProductInStock = 10,
                            ProductID = 10,
                            Stock = 4
                        },
                        new
                        {
                            IDProductInStock = 11,
                            ProductID = 11,
                            Stock = 16
                        },
                        new
                        {
                            IDProductInStock = 12,
                            ProductID = 12,
                            Stock = 6
                        },
                        new
                        {
                            IDProductInStock = 13,
                            ProductID = 13,
                            Stock = 17
                        },
                        new
                        {
                            IDProductInStock = 14,
                            ProductID = 14,
                            Stock = 8
                        },
                        new
                        {
                            IDProductInStock = 15,
                            ProductID = 15,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 16,
                            ProductID = 16,
                            Stock = 7
                        },
                        new
                        {
                            IDProductInStock = 17,
                            ProductID = 17,
                            Stock = 3
                        },
                        new
                        {
                            IDProductInStock = 18,
                            ProductID = 18,
                            Stock = 18
                        },
                        new
                        {
                            IDProductInStock = 19,
                            ProductID = 19,
                            Stock = 0
                        },
                        new
                        {
                            IDProductInStock = 20,
                            ProductID = 20,
                            Stock = 17
                        },
                        new
                        {
                            IDProductInStock = 21,
                            ProductID = 21,
                            Stock = 17
                        },
                        new
                        {
                            IDProductInStock = 22,
                            ProductID = 22,
                            Stock = 17
                        },
                        new
                        {
                            IDProductInStock = 23,
                            ProductID = 23,
                            Stock = 9
                        },
                        new
                        {
                            IDProductInStock = 24,
                            ProductID = 24,
                            Stock = 0
                        },
                        new
                        {
                            IDProductInStock = 25,
                            ProductID = 25,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 26,
                            ProductID = 26,
                            Stock = 6
                        },
                        new
                        {
                            IDProductInStock = 27,
                            ProductID = 27,
                            Stock = 17
                        },
                        new
                        {
                            IDProductInStock = 28,
                            ProductID = 28,
                            Stock = 15
                        },
                        new
                        {
                            IDProductInStock = 29,
                            ProductID = 29,
                            Stock = 18
                        },
                        new
                        {
                            IDProductInStock = 30,
                            ProductID = 30,
                            Stock = 0
                        },
                        new
                        {
                            IDProductInStock = 31,
                            ProductID = 31,
                            Stock = 12
                        },
                        new
                        {
                            IDProductInStock = 32,
                            ProductID = 32,
                            Stock = 12
                        },
                        new
                        {
                            IDProductInStock = 33,
                            ProductID = 33,
                            Stock = 8
                        },
                        new
                        {
                            IDProductInStock = 34,
                            ProductID = 34,
                            Stock = 19
                        },
                        new
                        {
                            IDProductInStock = 35,
                            ProductID = 35,
                            Stock = 12
                        },
                        new
                        {
                            IDProductInStock = 36,
                            ProductID = 36,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 37,
                            ProductID = 37,
                            Stock = 6
                        },
                        new
                        {
                            IDProductInStock = 38,
                            ProductID = 38,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 39,
                            ProductID = 39,
                            Stock = 12
                        },
                        new
                        {
                            IDProductInStock = 40,
                            ProductID = 40,
                            Stock = 19
                        },
                        new
                        {
                            IDProductInStock = 41,
                            ProductID = 41,
                            Stock = 8
                        },
                        new
                        {
                            IDProductInStock = 42,
                            ProductID = 42,
                            Stock = 6
                        },
                        new
                        {
                            IDProductInStock = 43,
                            ProductID = 43,
                            Stock = 15
                        },
                        new
                        {
                            IDProductInStock = 44,
                            ProductID = 44,
                            Stock = 12
                        },
                        new
                        {
                            IDProductInStock = 45,
                            ProductID = 45,
                            Stock = 3
                        },
                        new
                        {
                            IDProductInStock = 46,
                            ProductID = 46,
                            Stock = 13
                        },
                        new
                        {
                            IDProductInStock = 47,
                            ProductID = 47,
                            Stock = 11
                        },
                        new
                        {
                            IDProductInStock = 48,
                            ProductID = 48,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 49,
                            ProductID = 49,
                            Stock = 15
                        },
                        new
                        {
                            IDProductInStock = 50,
                            ProductID = 50,
                            Stock = 9
                        },
                        new
                        {
                            IDProductInStock = 51,
                            ProductID = 51,
                            Stock = 3
                        },
                        new
                        {
                            IDProductInStock = 52,
                            ProductID = 52,
                            Stock = 15
                        },
                        new
                        {
                            IDProductInStock = 53,
                            ProductID = 53,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 54,
                            ProductID = 54,
                            Stock = 3
                        },
                        new
                        {
                            IDProductInStock = 55,
                            ProductID = 55,
                            Stock = 18
                        },
                        new
                        {
                            IDProductInStock = 56,
                            ProductID = 56,
                            Stock = 9
                        },
                        new
                        {
                            IDProductInStock = 57,
                            ProductID = 57,
                            Stock = 14
                        },
                        new
                        {
                            IDProductInStock = 58,
                            ProductID = 58,
                            Stock = 5
                        },
                        new
                        {
                            IDProductInStock = 59,
                            ProductID = 59,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 60,
                            ProductID = 60,
                            Stock = 0
                        },
                        new
                        {
                            IDProductInStock = 61,
                            ProductID = 61,
                            Stock = 19
                        },
                        new
                        {
                            IDProductInStock = 62,
                            ProductID = 62,
                            Stock = 15
                        },
                        new
                        {
                            IDProductInStock = 63,
                            ProductID = 63,
                            Stock = 16
                        },
                        new
                        {
                            IDProductInStock = 64,
                            ProductID = 64,
                            Stock = 11
                        },
                        new
                        {
                            IDProductInStock = 65,
                            ProductID = 65,
                            Stock = 18
                        },
                        new
                        {
                            IDProductInStock = 66,
                            ProductID = 66,
                            Stock = 2
                        },
                        new
                        {
                            IDProductInStock = 67,
                            ProductID = 67,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 68,
                            ProductID = 68,
                            Stock = 4
                        },
                        new
                        {
                            IDProductInStock = 69,
                            ProductID = 69,
                            Stock = 13
                        },
                        new
                        {
                            IDProductInStock = 70,
                            ProductID = 70,
                            Stock = 5
                        },
                        new
                        {
                            IDProductInStock = 71,
                            ProductID = 71,
                            Stock = 7
                        },
                        new
                        {
                            IDProductInStock = 72,
                            ProductID = 72,
                            Stock = 6
                        },
                        new
                        {
                            IDProductInStock = 73,
                            ProductID = 73,
                            Stock = 1
                        },
                        new
                        {
                            IDProductInStock = 74,
                            ProductID = 74,
                            Stock = 8
                        },
                        new
                        {
                            IDProductInStock = 75,
                            ProductID = 75,
                            Stock = 17
                        },
                        new
                        {
                            IDProductInStock = 76,
                            ProductID = 76,
                            Stock = 2
                        },
                        new
                        {
                            IDProductInStock = 77,
                            ProductID = 77,
                            Stock = 15
                        },
                        new
                        {
                            IDProductInStock = 78,
                            ProductID = 78,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 79,
                            ProductID = 79,
                            Stock = 14
                        },
                        new
                        {
                            IDProductInStock = 80,
                            ProductID = 80,
                            Stock = 0
                        },
                        new
                        {
                            IDProductInStock = 81,
                            ProductID = 81,
                            Stock = 0
                        },
                        new
                        {
                            IDProductInStock = 82,
                            ProductID = 82,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 83,
                            ProductID = 83,
                            Stock = 4
                        },
                        new
                        {
                            IDProductInStock = 84,
                            ProductID = 84,
                            Stock = 9
                        },
                        new
                        {
                            IDProductInStock = 85,
                            ProductID = 85,
                            Stock = 9
                        },
                        new
                        {
                            IDProductInStock = 86,
                            ProductID = 86,
                            Stock = 5
                        },
                        new
                        {
                            IDProductInStock = 87,
                            ProductID = 87,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 88,
                            ProductID = 88,
                            Stock = 18
                        },
                        new
                        {
                            IDProductInStock = 89,
                            ProductID = 89,
                            Stock = 15
                        },
                        new
                        {
                            IDProductInStock = 90,
                            ProductID = 90,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 91,
                            ProductID = 91,
                            Stock = 13
                        },
                        new
                        {
                            IDProductInStock = 92,
                            ProductID = 92,
                            Stock = 10
                        },
                        new
                        {
                            IDProductInStock = 93,
                            ProductID = 93,
                            Stock = 5
                        },
                        new
                        {
                            IDProductInStock = 94,
                            ProductID = 94,
                            Stock = 7
                        },
                        new
                        {
                            IDProductInStock = 95,
                            ProductID = 95,
                            Stock = 17
                        },
                        new
                        {
                            IDProductInStock = 96,
                            ProductID = 96,
                            Stock = 5
                        },
                        new
                        {
                            IDProductInStock = 97,
                            ProductID = 97,
                            Stock = 1
                        },
                        new
                        {
                            IDProductInStock = 98,
                            ProductID = 98,
                            Stock = 15
                        },
                        new
                        {
                            IDProductInStock = 99,
                            ProductID = 99,
                            Stock = 12
                        },
                        new
                        {
                            IDProductInStock = 100,
                            ProductID = 100,
                            Stock = 14
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
